jest.mock('react-native', () => ({
  NativeModules: {
    MarfeelSdk: {
      initialize: jest.fn(),
      trackNewPage: jest.fn(),
      trackScreen: jest.fn(),
      stopTracking: jest.fn(),
      setLandingPage: jest.fn(),
      setSiteUserId: jest.fn(),
      getUserId: jest.fn().mockResolvedValue('test-user-id'),
      setUserType: jest.fn(),
      getRFV: jest.fn().mockResolvedValue('{"rfv":0.5,"r":1,"f":2,"v":3}'),
      setPageVar: jest.fn(),
      setPageMetric: jest.fn(),
      setSessionVar: jest.fn(),
      setUserVar: jest.fn(),
      addUserSegment: jest.fn(),
      setUserSegments: jest.fn(),
      removeUserSegment: jest.fn(),
      clearUserSegments: jest.fn(),
      trackConversion: jest.fn(),
      setConsent: jest.fn(),
      initializeMultimediaItem: jest.fn(),
      registerMultimediaEvent: jest.fn(),
    },
  },
  Platform: {
    select: jest.fn((obj) => obj.default || obj.ios),
  },
  findNodeHandle: jest.fn(() => 123),
  ScrollView: 'ScrollView',
  FlatList: 'FlatList',
  SectionList: 'SectionList',
}));
